[package]
name = "hlist-macro"
version = "0.1.0"
authors = ["kyren <catherine@chucklefish.org>"]
repository = "https://github.com/chucklefish/hlist-macro"
description = "Heterogeneous list data-types and macros"
readme = "README"
license = "MIT"
